version: '2'

services:
  drupal:
    build:
      context: .
      args: 
        - buildno: 1
        - gitcommithash: test33f
      dockerfile: Dockerfile
    image: custom-drupal
    ports:
      - '8080:80'
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes
    
  DB:
    image: postgres:12.1
    environment: 
      - POSTGRES_PASSWORD=Singtel2021
      - POSTGRES_DB=test
    volumes:
      - postgres_db:/var/list/postgresql/data

volumes:
  postgres_db:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
